<h1>Add Meetup</h1>

<?php
$form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>
<br/>
<div class="form-group">
    <label for="title">Title</label><br />
    <?= $this->formRow($form->get('title')) ?>
</div>
<div class="form-group">
    <label for="description">Description</label><br />
    <?= $this->formRow($form->get('description')) ?>
</div>
<div class="form-group">
    <label for="startTime">Start Time</label><br />
    <?= $this->formRow($form->get('startTime')) ?>
</div>
<div class="form-group">
    <label for="endTime">End Time</label>
    <?= $this->formRow($form->get('endTime')) ?>
</div>
<?= $this->formInput($form->get('submit')) ?>
<br/>
<?= $this->form()->closeTag($form); ?>

