    <div class="row">
        <h1>Meetup Lists</h1>
    </div>

    <table class="table table-striped table-responsive table-bordered">
        <thead>
            <tr>
                <th>ID</th><th>Titre</th><th>Description</th><th>Start Time</th><th>End Time</th><th>Details</th></th><th>Edit</th><th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->meetups as $meetup): /* @var $meetup \Meetup\Entity\Meetup */ ?>

                <?php
                    $id = $meetup->getId();
                    $title = $meetup->getTitle();
                    $description = $meetup->getDescription();
                    $startTime = $meetup->getStartTime()->format('Y-m-d');
                    $endTime = $meetup->getEndTime()->format('Y-m-d');
                ?>

                <tr>
                    <td><?= $id ?></td>
                    <td><?= $title ?></td>
                    <td><?= $description ?></td>
                    <td><?= $startTime ?></td>
                    <td><?= $endTime ?></td>

                    <?php
                    $detail_url = $this->url('meetups/detail');
                    $detail_url = $detail_url.'/'.$id;
                    $update_url = $this->url('meetups/update');
                    $update_url = $update_url.'/'.$id;
                    $delete_url = $this->url('meetups/delete');
                    $delete_url = $delete_url.'/'.$id;
                    ?>
                    <td><a href="<?= $detail_url ?>" type="button" class="btn btn-info"><span class="glyphicon glyphicon-zoom-in" aria-hidden="true"></span></a></td>
                    <td><a href="<?= $update_url ?>" type="button" class="btn btn-warning"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
                    <td><a type="button" class="btn btn-danger" data-toggle="modal" data-target="#delete<?= $id ?>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a></td>



                    <!-- Delete Modal-->
                    <div class="modal fade" id="delete<?= $id ?>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h3 class="modal-title" id="exampleModalLabel">Delete Event <?= $meetup->getTitle() ?></h3>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true" class="pull-right">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    You will delete finally this meetup, are you sure ?
                                </div>
                                <div class="modal-footer">
                                    <a href="<?= $delete_url ?>" type="button" class="btn btn-danger">Delete</a>
                                    <a href="#" type="button" class="btn btn-default" data-dismiss="modal">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- End Delete Modal-->

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>


